name: imdb_scraper
on:
  schedule:
    - cron: '*/5 * * * *' # runs every 5 minutes (test)
jobs:
  build:
    runs-on: ubuntu-latest
    steps:

          - name: checkout repo content
            uses: actions/checkout@v2 # checkout the repository content to github runner
              
          - name: install python packages
            run: sh run.sh

          - name: run py script # run scrape_data.py to get the latest IMDB top 1000 movie data
            run: python scrape_data.py
              
          - name: commit files
            run: |
              git config --local user.email "action@github.com"
              git config --local user.name "GitHub Action"
              git add -A
              git commit -m "update data" -a
          - name: push changes
            uses: ad-m/github-push-action@v0.6.0
            with:
              github_token: ${{ secrets.GITHUB_TOKEN }}
              branch: main